### ISSUE TITLE
Data toegevoegd aan header, ook optioneel kunnen toevoegen aan data file

### ISSUE THREAD

**Issue by ChrisTNO** [Deltares-research/geost#11]
Bij het toepassen van bepaalde functies zoals: 

lat_values = geost.spatial.get_raster_values(
    dino_boreholes_selected.header["x"],
    dino_boreholes_selected.header["y"],
    bathy
)

dino_boreholes_selected.header["LAT_depth"] = lat_values

en

dino_boreholes_selected.get_area_labels(toppl, "TOP_PL", include_in_header=True)

HIerbij is het heel makkelijk om deze data toe te voegen aan de header. Echter voor verdere stappen is het vaak heel handig om deze toevoegingen aan de data zelf te doen. Om dit als optie te hebben, zou erg handig zijn.

**Comment by Erik-Geo** [comment]
Toegevoegd in [deze commit](https://github.com/Deltares-research/geost/commit/9e1c6ff1a1394a677c8b290c0ba0a9c402a82ad5)

**Comment by Erik-Geo** [comment]
Toegevoegd in [deze commit](https://github.com/Deltares-research/geost/commit/9e1c6ff1a1394a677c8b290c0ba0a9c402a82ad5)
