### ISSUE TITLE
Remove use of to_collection() in Collection

### ISSUE THREAD

**Issue by smknaake** [Deltares-research/geost#35]
Remove the use of the `to_collection()` method in selection methods of the Collection class. This always returns a new Header object with only "nr", "x", "y", "surface", "end", "geometry" and removes any possible additional information that is present in the Header.

Suggested fix: use the `Header.get()` to select the unique selected "nr"s  from the Header. The fix however must include that the type of Collection that is returned is derived from the type of data (e.g. borehole, CPT) that is being worked with.

Collection methods where this occurs:
- `select_by_values()`
- `slice_depth_interval()`
- `slice_by_values()`
- `select_by_condition()`

**Comment by Erik-Geo** [comment]
Resolved in 108d0b1074bc40a65f5b26b2469d6508bbddd061
