### ISSUE TITLE
Fix inefficient get_cumulative_layer_thickness

### ISSUE THREAD

**Issue by smknaake** [Deltares-research/geost#8]
Using `PointDataCollection.get_cumulative_layer_thickness()` is inefficient when multiple values are used as input e.g.:

```
glauc_thickness = cores.get_cumulative_layer_thickness(
    'glaucfr', ['GC0', 'GC1', 'GC2', 'GC3', 'GC4', 'GC5', 'GCX']
    )
```

This:
- Loops over each borehole and checks for value 'GC0'
- Next step: Loop over each borehole again and check for value 'GC1'
- etc.

Needs to be: Loop over each borehole and check for each value.

**Comment by Erik-Geo** [comment]
Note: same logic is used in `PointDataCollection.get_layer_top()`
